import { Post } from "src/app/interface/post";

export const postData: Post[] = [
    {
        postId: 0,
        title: 'Bar opening in Paris',
        imageUrl: './assets/bar/bar-3.jpeg',
        content: "",
        creationDate: new Date(),
        likes: 0,
        dislikes: 0,
        comment: [],
    },
    {
        postId: 1,
        title: 'Ballerina photoshoot in NYC',
        imageUrl: './assets/ballerina/ballerina-4.jpeg',
        content: "",
        creationDate: new Date(),
        likes: 0,
        dislikes: 0,
        comment: [],
    },
    {
        postId: 2,
        title: 'Designer behind the scenes',
        imageUrl: './assets/designer/designer-4.jpeg',
        content: "",
        creationDate: new Date(),
        likes: 0,
        dislikes: 0,
        comment: [],

    },
    {
        postId: 3,
        title: 'Fashion show in India',
        imageUrl: './assets/india/india-hidden.jpeg',
        content: "",
        creationDate: new Date(),
        likes: 0,
        dislikes: 0,
        comment: [],
    },
    {
        postId: 4,
        title: 'Photoshot for Japan\'s national day',
        imageUrl: '../assets/japan/japan-model.jpeg',
        content: "",
        creationDate: new Date(),
        likes: 0,
        dislikes: 0,
        comment: [],
    },
    {
        postId: 5,
        title: 'My friends new brand H33y',
        imageUrl: '../assets/new-brand/brand-2.jpeg',
        content: "",
        creationDate: new Date(),
        likes: 0,
        dislikes: 0,
        comment: [],
    },
    {
        postId: 6,
        title: 'Water sirens',
        imageUrl: './assets/water/water-3.jpeg',
        content: "",
        creationDate: new Date(),
        likes: 0,
        dislikes: 0,
        comment: [],
    },
    {
        postId: 7,
        title: 'Marketing images for a new play',
        imageUrl: './assets/student/art-study.jpeg',
        content: "",
        creationDate: new Date(),
        likes: 0,
        dislikes: 0,
        comment: [],
    },
];
